version: "3.8"

services:
  klipper:
    # image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    # if klipper cannot connect to the printer check permissions on rpi then add the group here
    # group_add:
    #   - "996"
    #   - "998"
    cap_add:
      - SYS_NICE
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.printer == true]
    volumes:
      - gcode_files:/home/klippy/gcode_files
      # be aware to create your own branch if you mount the config folder as it will be updated on the main branch
      # that way you can merge upstream changes to your customized configs
      - ./config:/home/klippy/.config
      - moonraker_data:/home/klippy/.moonraker_database
      # - <<your_config_path>>:/home/klippy/.config
      # - ./printer.cfg:/home/klippy/.config/printer.cfg
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices/platform/soc/fe200000.gpio/:/sys/devices/platform/soc/fe200000.gpio/
    networks:
      - klipper_internal
    # mount serial device - take care to grant sufficient permissions to the device: <host_dev>:<container_dev>
    # put <container_dev> into your printer.cfg
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32f103xe_39FFD2054246303718661857-if00:/dev/serial/by-id/usb-Klipper_stm32f103xe_39FFD2054246303718661857-if00
      - /dev/video0:/dev/video0
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiomem:/dev/gpiomem

  mainsail:
    image: dimalo/mainsail
    build:
      dockerfile: Dockerfile
      context: frontend
      args:
        FRONTEND_ZIP_URL: https://github.com/meteyou/mainsail/releases/latest/download/mainsail.zip
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - klipper
      # - klipper_another_printer
    links:
      - klipper:klipper
      # - klipper_another_printer:klipper_another_printer
    networks:
      - public
      - klipper_internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.mainsail.rule=Host(`mainsail.kureta.xyz`)
      - traefik.http.routers.mainsail.entrypoints=websecure
      - traefik.http.routers.mainsail.tls.certresolver=myresolver

volumes:
  gcode_files:
  moonraker_data:

networks:
  public:
    external: true
  klipper_internal:
    external: false
